//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NSerio.FileValidation.Agents.Database.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	COUNT(*)
        ///  FROM 
        ///	[EDDSDBO].[ZCodeArtifact_{0}] WITH (NOLOCK)
        ///WHERE
        ///	AssociatedArtifactID = {1}.
        /// </summary>
        public static string CheckForFileType {
            get {
                return ResourceManager.GetString("CheckForFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///ISNULL(SavedSearch,0) AS SavedSearch
        ///FROM 
        ///EDDSDBO.FileValidationJob
        ///WHERE
        ///ArtifactID = {0}.
        /// </summary>
        public static string CheckForJobSS {
            get {
                return ResourceManager.GetString("CheckForJobSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [EDDS]
        ///SELECT ArtifactID FROM EDDSDBO.[ExtendedCase] WHERE ArtifactID = {0}.
        /// </summary>
        public static string CheckIfCaseStillExists {
            get {
                return ResourceManager.GetString("CheckIfCaseStillExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [EDDS]
        ///DELETE FROM EDDSDBO.FileValidator_CasesQueue WHERE CaseArtifactID = {0}.
        /// </summary>
        public static string CleanupDeletedCaseFromManagerQueue {
            get {
                return ResourceManager.GetString("CleanupDeletedCaseFromManagerQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [EDDS]
        ///WHILE (SELECT TOP 1 ID FROM EDDSDBO.FileValidator_DocumentQueue WHERE CaseArtifactID = {1}) &gt; 0
        ///BEGIN
        ///	DELETE TOP ({0})
        ///	FROM EDDSDBO.FileValidator_DocumentQueue
        ///	WHERE CaseArtifactID = {1}
        ///END.
        /// </summary>
        public static string CleanupDeletedCaseFromWorkerQueue {
            get {
                return ResourceManager.GetString("CleanupDeletedCaseFromWorkerQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF (EXISTS (SELECT * 
        ///                 FROM INFORMATION_SCHEMA.TABLES 
        ///                 WHERE TABLE_SCHEMA = &apos;EDDSDBO&apos; 
        ///                 AND  TABLE_NAME = &apos;FileValidator_SavedSearchData&apos;))
        ///BEGIN
        ///DROP TABLE eddsdbo.FileValidator_SavedSearchData
        ///END.
        /// </summary>
        public static string DeleteSSTable {
            get {
                return ResourceManager.GetString("DeleteSSTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [EDDS]
        ///SELECT TOP 1 ID
        ///FROM EDDSDBO.[FileValidator_FileValidator_DocumentQueue] WITH(NOLOCK)
        ///WHERE [CaseArtifactID] = {0}
        ///	AND [JobArtifactID] = {1}.
        /// </summary>
        public static string DoQueueRecordsExist {
            get {
                return ResourceManager.GetString("DoQueueRecordsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INNER JOIN
        ///	EDDSDBO.[File] WITH (NOLOCK)
        ///	ON
        ///	EDDSDBO.Document.ArtifactID = EDDSDBO.[File].DocumentArtifactID
        ///WHERE
        ///	EDDSDBO.[File].[Type] IN(
        ///SELECT 
        ///	CASE [EDDSDBO].[Code].[Name] WHEN &apos;Native&apos; THEN 0 WHEN &apos;Image&apos; THEN 1 WHEN &apos;Produced Image&apos; THEN 2 END AS FileType
        ///  FROM 
        ///	[EDDSDBO].[ZCodeArtifact_{0}] WITH (NOLOCK)
        ///INNER JOIN
        ///	[EDDSDBO].[Code] WITH (NOLOCK)
        ///	ON
        ///	[EDDSDBO].[ZCodeArtifact_{0}].CodeArtifactID = [EDDSDBO].[Code].ArtifactID
        ///WHERE
        ///	[EDDSDBO].[ZCodeArtifact_{0}].AssociatedArtifac [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FileTypeFilter {
            get {
                return ResourceManager.GetString("FileTypeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [EDDSDBO].[FileValidator_MissingFiles]
        ///	(
        ///		[TimeStamp], 
        ///		DocumentArtifactID, 
        ///		FilePath, 
        ///		FileType
        ///	)
        ///VALUES 
        ///	(
        ///		GetUTCDate(),
        ///		@DocumentArtifactID,
        ///		@FilePath,
        ///		@FileType
        ///	).
        /// </summary>
        public static string InsertMissingRecords {
            get {
                return ResourceManager.GetString("InsertMissingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [EDDS]
        ///DELETE
        ///FROM EDDSDBO.[FileValidator_CasesQueue]
        ///WHERE CaseArtifactID = {0}
        ///	AND JobArtifactID = {1}.
        /// </summary>
        public static string RemoveFromCasesQueue {
            get {
                return ResourceManager.GetString("RemoveFromCasesQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [EDDS]
        ///DELETE FROM [eddsdbo].[FileValidator_DocumentQueue]
        ///WHERE [ID] = {0}.
        /// </summary>
        public static string RemoveFromDocumentQueue {
            get {
                return ResourceManager.GetString("RemoveFromDocumentQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [EDDSDBO].FileValidator_MissingFiles.
        /// </summary>
        public static string RemoveFromMissingFiles {
            get {
                return ResourceManager.GetString("RemoveFromMissingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ArtifactID
        ///FROM [EDDSDBO].ArtifactGuid 
        ///WHERE ArtifactGuid = &apos;{0}&apos;.
        /// </summary>
        public static string RetrieveArtifactIDByGuid {
            get {
                return ResourceManager.GetString("RetrieveArtifactIDByGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///		{0} CaseArtifactID,
        ///		{1} JobArtifactID,
        ///		NULL AgentID,
        ///		GetUTCDate() [TimeStamp],
        ///		0 [Status],
        ///		EDDSDBO.[Document].ArtifactID DocumentArtifactID 
        ///	FROM EDDSDBO.[Document] WITH(NOLOCK).
        /// </summary>
        public static string RetrieveDocuments {
            get {
                return ResourceManager.GetString("RetrieveDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	F.DOCUMENTARTIFACTID, 
        ///	F.[GUID] FileGuid, 
        ///	F.LOCATION, 
        ///	CASE F.[Type] 
        ///		WHEN 0 THEN &apos;Native&apos; 
        ///		WHEN 1 THEN &apos;Image&apos; 
        ///		WHEN 2 THEN &apos;Full Text&apos; 
        ///		WHEN 3 THEN &apos;Production Image&apos;  
        ///		WHEN 4 THEN &apos;Transcript&apos; 
        ///		WHEN 5 THEN &apos;Production Image Placeholder&apos; 
        ///		ELSE &apos;Other&apos;	
        ///	END As FileType 
        ///FROM EDDSDBO.[File] F WITH(NOLOCK) 
        ///	INNER JOIN EDDSDBO.[Document] D WITH(NOLOCK) ON F.DocumentArtifactID = D.ArtifactID 
        ///WHERE D.ArtifactID = {0}.
        /// </summary>
        public static string RetrieveFiles {
            get {
                return ResourceManager.GetString("RetrieveFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [EDDS]
        ///SET NOCOUNT ON 
        ///BEGIN TRAN 
        ///	SELECT TOP ({0})
        ///		[ID]
        ///	INTO #FileValidator_TempTable
        ///	FROM [FileValidator_DocumentQueue] WITH(UPDLOCK,READPAST) 
        ///	WHERE [AgentID] IS NULL
        ///		AND [Status] = 0
        ///		AND [CaseArtifactID] = {2}
        ///		AND [JobArtifactID] = {3}
        ///	ORDER BY [ID]
        ///
        ///	UPDATE [FileValidator_DocumentQueue]
        ///	SET [AgentID] = {1}, [Status] = 1 
        ///	WHERE [ID] IN 
        ///		(
        ///			SELECT [ID] 
        ///			FROM #FileValidator_TempTable
        ///		)
        ///
        ///	SELECT 
        ///		[ID]
        ///		,[CaseArtifactID]
        ///		,[JobArtifactID]
        ///		,[AgentID] [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RetrieveNextRecords {
            get {
                return ResourceManager.GetString("RetrieveNextRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [EDDS]
        ///
        ///UPDATE eddsdbo.[FileValidator_CasesQueue] WITH (UPDLOCK)
        ///SET AgentID = {0}
        ///OUTPUT
        ///		Deleted.[ID],
        ///		Deleted.[CaseArtifactID],
        ///		Deleted.[JobArtifactID],
        ///		Deleted.[Status],
        ///		Deleted.[FlagFieldColumnName]
        ///WHERE ID = (SELECT TOP 1 ID
        ///			FROM  eddsdbo.[FileValidator_CasesQueue] WITH (NOLOCK)
        ///			WHERE
        ///			[Status] = 1
        ///			AND AgentID = {0}
        ///			OR AgentID IS NULL
        ///			ORDER BY [TimeStamp]).
        /// </summary>
        public static string RetrieveNextWorkspace {
            get {
                return ResourceManager.GetString("RetrieveNextWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [EDDS]
        ///SELECT TOP ({0})
        ///		[ID]
        ///      ,[CaseArtifactID]
        ///      ,[JobArtifactID]
        ///      ,[AgentID]
        ///      ,[TimeStamp]
        ///      ,[Status]
        ///      ,[DocumentArtifactID]
        ///  FROM EDDSDBO.[FileValidator_DocumentQueue] WITH(NOLOCK)
        ///  WHERE [AgentID] = {1}
        ///	AND [Status] = 1
        ///	AND [CaseArtifactID] = {2}
        ///	AND [JobArtifactID] = {3}
        ///  ORDER BY [ID].
        /// </summary>
        public static string RetrieveUnfinishedRecords {
            get {
                return ResourceManager.GetString("RetrieveUnfinishedRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [EDDS]
        ///SELECT 
        ///	[ID],
        ///	[CaseArtifactID],
        ///	[JobArtifactID],
        ///	[Status],
        ///	[FlagFieldColumnName]
        ///FROM eddsdbo.[FileValidator_CasesQueue] WITH(NOLOCK)
        ///ORDER BY [TimeStamp].
        /// </summary>
        public static string RetrieveWorkspaces {
            get {
                return ResourceManager.GetString("RetrieveWorkspaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INNER JOIN eddsdbo.FileValidator_SavedSearchData ON eddsdbo.Document.ArtifactID = eddsdbo.FileValidator_SavedSearchData.ArtifactID.
        /// </summary>
        public static string SavedSearchFilter {
            get {
                return ResourceManager.GetString("SavedSearchFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [EDDS]
        ///UPDATE EDDSDBO.[FileValidator_CasesQueue]
        ///SET Status = {0}
        ///WHERE CaseArtifactID = {1}
        ///	AND JobArtifactID = {2}.
        /// </summary>
        public static string UpdateCasesQueue {
            get {
                return ResourceManager.GetString("UpdateCasesQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE EDDSDBO.[Document] SET {0} = {1} WHERE ArtifactID = {2}.
        /// </summary>
        public static string UpdateFlagFile {
            get {
                return ResourceManager.GetString("UpdateFlagFile", resourceCulture);
            }
        }
    }
}
