//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NSerio.FileValidation.EventHandlers.Database.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [EDDS]
        ///IF OBJECT_ID(&apos;FileValidator_CasesQueue&apos;) IS NULL BEGIN 
        ///	CREATE TABLE [FileValidator_CasesQueue]
        ///		( 
        ///			[ID] INT IDENTITY(1,1),
        ///			[CaseArtifactID] [int] NOT NULL,
        ///			[JobArtifactID] INT NOT NULL,
        ///			[TimeStamp] [datetime] NOT NULL,
        ///			[Status] INT NOT NULL,
        ///			[FlagFieldColumnName] VARCHAR(100),
        ///            [AgentID] [int] NULL
        ///		) 
        ///END
        ///ELSE
        ///BEGIN
        ///	IF NOT EXISTS(
        ///    SELECT *
        ///    FROM sys.columns 
        ///    WHERE Name      = N&apos;AgentID&apos;
        ///      AND Object_ID = Object_ID(N&apos;FileValidato [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CreateCasesQueueTable {
            get {
                return ResourceManager.GetString("CreateCasesQueueTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [EDDS]
        ///IF OBJECT_ID(&apos;FileValidator_DocumentQueue&apos;) IS NULL BEGIN 
        ///	CREATE TABLE [FileValidator_DocumentQueue]
        ///		( 
        ///			[ID] INT IDENTITY(1,1),
        ///			[CaseArtifactID] [int] NULL,
        ///			[JobArtifactID] [int] NULL,
        ///			[AgentID] INT NULL, 
        ///			[TimeStamp] [datetime] NOT NULL,
        ///			[Status] [BIT] NOT NULL,
        ///			[DocumentArtifactID] INT NOT NULL
        ///		) 
        ///END.
        /// </summary>
        public static string CreateDocumentQueueTable {
            get {
                return ResourceManager.GetString("CreateDocumentQueueTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [EDDS]
        ///IF NOT EXISTS 
        ///	(
        ///		SELECT OBJECT_ID
        ///		FROM sys.indexes 
        ///		WHERE name=&apos;IX_FileValidator_CasesQueue_ID&apos; 
        ///			AND object_id = OBJECT_ID(&apos;FileValidator_CasesQueue&apos;)
        ///	)
        ///BEGIN
        ///	CREATE CLUSTERED INDEX IX_FileValidator_CasesQueue_ID ON [FileValidator_CasesQueue]([ID])
        ///END.
        /// </summary>
        public static string CreateIndexOnCasesQueue {
            get {
                return ResourceManager.GetString("CreateIndexOnCasesQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [EDDS]
        ///IF NOT EXISTS 
        ///	(
        ///		SELECT OBJECT_ID
        ///		FROM sys.indexes 
        ///		WHERE name=&apos;IX_FileValidator_DocumentQueue_ID&apos; 
        ///			AND object_id = OBJECT_ID(&apos;FileValidator_DocumentQueue&apos;)
        ///	)
        ///BEGIN
        ///	CREATE CLUSTERED INDEX IX_FileValidator_DocumentQueue_ID ON [FileValidator_DocumentQueue]([ID])
        ///END.
        /// </summary>
        public static string CreateIndexOnDocumentQueue {
            get {
                return ResourceManager.GetString("CreateIndexOnDocumentQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF OBJECT_ID(&apos;FileValidator_MissingFiles&apos;) IS NULL BEGIN 
        ///	CREATE TABLE [FileValidator_MissingFiles]
        ///		( 
        ///			[ID] INT IDENTITY(1,1),
        ///			[TimeStamp] DATETIME,
        ///			[DocumentArtifactID] INT,
        ///			[FilePath] NVARCHAR(2000),
        ///			[FileType] NVARCHAR(200)
        ///		) 
        ///END.
        /// </summary>
        public static string CreateMissingFilesTable {
            get {
                return ResourceManager.GetString("CreateMissingFilesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [EDDS]
        ///SELECT ID
        ///FROM [FileValidator_CasesQueue]
        ///WHERE CaseArtifactID = {0}
        ///	AND JobArtifactID = {1}.
        /// </summary>
        public static string DoesRecordExist {
            get {
                return ResourceManager.GetString("DoesRecordExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 
        ///	ArtifactID
        ///FROM [{0}].
        /// </summary>
        public static string DoesRecordExistAlready {
            get {
                return ResourceManager.GetString("DoesRecordExistAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [EDDS]
        ///INSERT INTO [FileValidator_CasesQueue]
        ///	(
        ///		[CaseArtifactID],
        ///		[JobArtifactID],
        ///		[TimeStamp],
        ///		[Status],
        ///		[FlagFieldColumnName]
        ///	)
        ///VALUES 
        ///	(
        ///	{0},
        ///	{1},
        ///	GETUTCDATE(),
        ///	0,
        ///	&apos;{2}&apos;
        ///	).
        /// </summary>
        public static string InsertIntoCasesQueue {
            get {
                return ResourceManager.GetString("InsertIntoCasesQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [EDDS]
        ///DELETE
        ///FROM [FileValidator_CasesQueue]
        ///WHERE CaseArtifactID = {0}
        ///	AND JobArtifactID = {1}.
        /// </summary>
        public static string RemoveFromCasesQueue {
            get {
                return ResourceManager.GetString("RemoveFromCasesQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [EDDS]
        ///DELETE
        ///FROM [FileValidator_DocumentQueue]
        ///WHERE CaseArtifactID = {0}
        ///	AND JobArtifactID = {1}.
        /// </summary>
        public static string RemoveFromDocumentQueue {
            get {
                return ResourceManager.GetString("RemoveFromDocumentQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ArtifactID
        ///FROM ArtifactGuid 
        ///WHERE ArtifactGuid = &apos;{0}&apos;.
        /// </summary>
        public static string RetrieveArtifactIDByGuid {
            get {
                return ResourceManager.GetString("RetrieveArtifactIDByGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ArtifactType
        ///FROM ArtifactType 
        ///WHERE ArtifactTypeID = {0}.
        /// </summary>
        public static string RetrieveArtifactTypeName {
            get {
                return ResourceManager.GetString("RetrieveArtifactTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &apos;[&apos; + AVF.ColumnName + &apos;]&apos;
        ///FROM Field F
        ///	INNER JOIN ArtifactViewField AVF ON F.ArtifactViewFieldID = AVF.ArtifactViewFieldID
        ///WHERE F.ArtifactID = {0}.
        /// </summary>
        public static string RetrieveColumnName {
            get {
                return ResourceManager.GetString("RetrieveColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [EDDS]
        ///UPDATE [FileValidator_CasesQueue]
        ///SET Status = {0}
        ///WHERE CaseArtifactID = {1}
        ///	AND JobArtifactID = {2}.
        /// </summary>
        public static string UpdateCasesQueue {
            get {
                return ResourceManager.GetString("UpdateCasesQueue", resourceCulture);
            }
        }
    }
}
